### ISSUE TITLE
Installation not working on Red Hat Linux supercomputer

### ISSUE THREAD

**Issue by justincbagley** [tkchafin/mpi-bucky#2]
Hi Tyler,
On an HPC cluster with Red Hat Linux with the following properties...

```
-bash-4.1$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:	6.6
Codename:	Santiago
```

Regular `make` install fails with the following error:

```
-bash-4.1$ make
mpic++ -O3 -std=c++11 -I. -o TaxonSet.o -c TaxonSet.C
mpic++ -O3 -std=c++11 -I. -o Alias.o -c Alias.C
mpic++ -O3 -std=c++11 -I. -o mbsumtree.o -c mbsumtree.C
mpic++ -O3 -std=c++11 -I. -o TGM.o -c TGM.C
mpic++ -O3 -std=c++11 -I. -o Quartets.o -c Quartets.C
mpic++ -O3 -std=c++11 -I. -o bucky bucky.C TaxonSet.o Alias.o mbsumtree.o TGM.o Quartets.o
bucky.C: In function 'void MPI_mcmcmc(std::vector<State*>&, std::vector<double>&, Rand*, std::vector<std::vector<int> >&, std::vector<std::vector<int> >&, int, const std::vector<int>&, const std::vector<int>&, int, int, std::vector<int>&, std::map<int, int>&, MPI_Comm)':
bucky.C:978:30: error: 'MPI' has not been declared
         MPI_Recv(&accept, 1, MPI::BOOL, recv_rank, 2, comm, MPI_STATUS_IGNORE);
                              ^
bucky.C:1018:30: error: 'MPI' has not been declared
         MPI_Send(&accept, 1, MPI::BOOL, send_rank, 2, comm);
                              ^
bucky.C: In function 'int main(int, char**)':
bucky.C:2103:3: error: 'MPI' has not been declared
   MPI::Init(argc, argv);
   ^
bucky.C:2105:13: error: 'MPI' has not been declared
   my_rank = MPI::COMM_WORLD.Get_rank(); //Get rank
             ^
bucky.C:2106:17: error: 'MPI' has not been declared
   MPI_Comm_size(MPI::COMM_WORLD, &p); //Get number of processes
                 ^
bucky.C:2183:13: error: 'MPI' has not been declared
   my_rank = MPI::COMM_WORLD.Get_rank();
             ^
make: *** [bucky] Error 1
-bash-4.1$ 
-bash-4.1$ 
```

Further context: modules are already loaded for openmpi and gcc v6.4. 

What's going wrong here? Could you please debug, or suggest a fix for this? It would be really great if you could carve out a little time to update the code and do a new release including a fix for this particular issue. Thanks for your help!
Best,
Justin

**Comment by justincbagley** [comment]
The line of code that is causing the problem is line 978 of bucky.C, which is as follows:

```
        MPI_Recv(&accept, 1, MPI::BOOL, recv_rank, 2, comm, MPI_STATUS_IGNORE);
```

Given this error point, does this mean that MPI::BOOL is incorrect or not being interpreted correctly by my version of openmpi? Is this old/outdated/misinterpreted fortran or C++ code?

Justin

**Comment by tkchafin** [comment]
Hi Justin, 

Yes, I think this is due to the code being outdated. What version of openmpi are you using? The C++ bindings are not build by default past version 2.0.0, so if you can rebuild openmpi and configure with "--enable-mpi-cxx" that might work. 

I had been meaning to covert to Boost::MPI, but never got around to it. Anyways, please let me know if rebuilding openmpi solves your problem and I can work on further debugging from there. 

Tyler

**Comment by justincbagley** [comment]
Hi Tyler, 

We only have openmpi 3 available as a preinstalled module on our cluster. I guess there are some other workarounds to try, such as installing an older version of openmpi in a virtual environment or prefixed local/user install. Do those sound like viable options? Are you sure that v2.0.0 is the latest version supporting C++ bindings you mentioned? If so, I'll give that a try and get back to you.

Justin

**Comment by tkchafin** [comment]
Hey Justin, 

Sorry for the delay, for some reason I'm not getting email notifications from github. The c++ bindings are deprecated and not installed by default with openmpi >2.0.0. The C++ compiler can still be built w/ >2.0.0, it just isn't by default.

Your HPC staff may have installed openmpi 3 with the c++ bindings already- you can check by loading the module and trying 'mpicxx -v' to see if the mpi c++ compiler is installed, and how it was configured. If not, you might be able to have them rebuild it as a separate module.

Alternatively, yeah you would need to either install openmpi >2.0.0 with the optional c++ bindings (I THINK this would be '--enable-mpi-cxx' added to the configure call but you'd need to double check on that), OR if you were going through the trouble you could just install openmpi <2.0.0. But I would definitely check if the already present openmpi module would work first.

Tyler
